# Generated by Django 5.1.4 on 2025-12-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Enter the full name of the contact person.",
                        max_length=255,
                        null=True,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Enter the name of the company.",
                        max_length=255,
                        null=True,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "company_email",
                    models.EmailField(
                        blank=True,
                        help_text="Enter the company's email address.",
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Company Email",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True,
                        help_text="Enter the contact person's mobile number.",
                        max_length=15,
                        null=True,
                        verbose_name="Mobile Number",
                    ),
                ),
                (
                    "plan_details",
                    models.CharField(
                        blank=True,
                        help_text="Enter the plan details (e.g., Pro, Basic).",
                        max_length=100,
                        null=True,
                        verbose_name="Plan Details",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        help_text="Enter the country code (e.g., 91).",
                        max_length=10,
                        null=True,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "is_event_management",
                    models.CharField(
                        blank=True,
                        help_text="Enter the country code (e.g., 91).",
                        max_length=10,
                        null=True,
                        verbose_name="Is Event Management",
                    ),
                ),
                (
                    "lead_capture_method",
                    models.CharField(
                        blank=True,
                        help_text="Enter the lead capture method (e.g., website, email).",
                        max_length=100,
                        null=True,
                        verbose_name="Lead Capture Method",
                    ),
                ),
                (
                    "annual_exhibitions",
                    models.CharField(
                        blank=True,
                        help_text="Enter the number of annual exhibitions.",
                        max_length=100,
                        null=True,
                        verbose_name="Annual Exhibitions",
                    ),
                ),
                (
                    "submission_timestamp",
                    models.CharField(
                        blank=True,
                        help_text="Enter the submission timestamp.",
                        max_length=100,
                        null=True,
                        verbose_name="Submission Timestamp",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the contact was created.",
                        verbose_name="Created Date",
                    ),
                ),
            ],
        ),
    ]
